name: Run posters script

on:
  schedule:
    - cron: '0 0 * * 1,3,5'

jobs:
  run_posters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run posters script on Monday, Wednesday, and Friday
      if: github.event.schedule.cron == '0 0 * * 1,3,5'
      run: |
        bash scripts/posters.sh openmetaverse fig-legal-policy 4
        bash scripts/posters.sh openmetaverse fig-AI 4
        bash scripts/posters.sh openmetaverse fig-networking 4
        bash scripts/posters.sh openmetaverse fig-security 4
        bash scripts/posters.sh openmetaverse fig-transactions 4
        bash scripts/posters.sh openmetaverse fig-users 4
        bash scripts/posters.sh openmetaverse fig-virtualworldsim 4
        bash scripts/posters.sh openmetaverse fig-digitalassets 4
        bash scripts/create-index.sh

    - name: Commit changes
      run: |
        git config --global user.name "madjin"
        git config --global user.email "32600939+madjin@users.noreply.github.com"
        git add -A .
        git commit -m "Run action runner"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
